---
- name: Set up a new server with user accounts, Fail2Ban, and UFW.
  hosts: all
  become: true
  tasks:
    - name: Update packages and system.
      include_tasks: "tasks/update-system.yml"
    - name: Set up `admin` users.
      include_tasks: "tasks/create-users.yml"
      tags:
        - create-users
    - name: Install Fail2Ban.
      include_tasks: "tasks/fail2ban.yml"
    - name: Install UFW.
      include_tasks: "tasks/ufw.yml"